defaults: &defaults
  host: ds031627.mongolab.com
  port: 31627
  username: scheduling
  password: scheduling
  database: scheduling

development:
  <<: *defaults

test:
  <<: *defaults

production:
  uri: <%= ENV['MONGOLAB_URI'] %>  

